import "./globals.css";
import {Metadata} from "next";

export const metadata = {
  title: "Churchment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
